# https://stackoverflow.com/questions/2090551/parse-query-string-in-javascript
# generated by js2coffee 2.1.0
getQueryVariable = (variable) ->
    query = window.location.search.substring(1)
    vars = query.split('&')
    i = 0
    while i < vars.length
        pair = vars[i].split('=')
        if decodeURIComponent(pair[0]) == variable
            return decodeURIComponent(pair[1])
        i++
    return

config =
    username: getQueryVariable('username')
    notify:
        chat: getQueryVariable('chat') || true
        subs: getQueryVariable('subs') || false
        subanniversary: getQueryVariable('subannv') || false
        hosts: getQueryVariable('hosts') || false
    emotes: getQueryVariable('emotes') || true
    subemotes: getQueryVariable('subemotes') || false
    bttvemotes: getQueryVariable('bttvemotes') || false
    maxmessages: getQueryVariable('maxmsgs') || 5

client = new irc.client
    options:
        debug: true
    connection:
        random: 'chat'
        reconnect: true
    channels: ['#' + config.username]

client.connect()

client.addListener 'chat', (channel, user, message) ->
    if config.notify.chat
        event = new CustomEvent('message', {'detail': {user: user, message: message, action: false}});
        document.dispatchEvent(event);